stages:
  - setup
  - test

variables:
  HF_HOME: ".cache/llama-cpp-python"

default:
  image: alpine:latest
  before_script:  
    - apk add --no-cache git build-base python3 python3-dev py3-pip py3-virtualenv
  cache:
    - &venv-cache
      key: "$CI_COMMIT_REF_NAME"
      paths:
        - .venv
      policy: pull
    - &llm-cache
      key: global
      paths:
        - .cache/llama-cpp-python
      policy: pull

setup:
  stage: setup
  script:
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install -r requirements.txt
    - python3 constants.py
  cache:
    - <<: *venv-cache
      policy: pull-push
    - <<: *llm-cache
      policy: pull-push

test:
  stage: test
  dependencies:
    - setup
  script:
    - source .venv/bin/activate
    - python3 test_imdb_reviews.py
  artifacts:
    paths:
      - results/
    expire_in: never
