stages:
  - setup
  - test

variables:
  HF_HOME: ".cache/llama-cpp-python"
  VENV_PATH: ".venv"

default:
  image: python:3.12-slim
  before_script:  
    - apt-get update
    - apt-get install -y gcc g++ build-essential git
  cache:
    - &venv-cache
      key: $CI_COMMIT_REF_NAME
      paths:
        - .venv
      policy: pull
    - &llm-cache
      key: global
      paths:
        - .cache/llama-cpp-python
      policy: pull

setup:
  stage: setup
  script:
    - python3 -m venv $VENV_PATH
    - source $VENV_PATH/bin/activate
    - pip install -r requirements.txt
    - python3 constants.py
  cache:
    - <<: *venv-cache
      policy: pull-push
    - <<: *llm-cache
      policy: pull-push

test:
  stage: test
  dependencies:
    - setup
  script:
    - source $VENV_PATH/bin/activate
    - python3 test_imdb_reviews.py
  artifacts:
    paths:
      - results/
    expire_in: never
