stages:
  - setup
  - test

variables:
  HF_HOME: ".cache/llama-cpp-python"
  VENV_PATH: ".venv"

default:
  image: python:3.12-alpine
  cache: &default-cache
    key: $CI_COMMIT_REF_NAME
    paths:
      - .cache/llama-cpp-python
      - .venv/
    policy: pull-push

setup:
  stage: setup
  script:
    - python3 -m venv $VENV_PATH
    - source $VENV_PATH/bin/activate
    - pip install -r requirements.txt

test:
  stage: test
  dependencies:
    - setup
  script:
    - source $VENV_PATH/bin/activate
    - python3 test_imdb_reviews.py
  artifacts:
    paths:
      - results/
    expire_in: never
  cache:
    <<: *default-cache
    policy: pull
